version: '3.8'

services:
  websocket-wss:
    build: .
    container_name: websocket-wss-server
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=cubevisservice.site
      - NODE_ENV=production
    volumes:
      # Certificados SSL do Let's Encrypt
      - /etc/letsencrypt/live/cubevisservice.site:/etc/letsencrypt/live/cubevisservice.site:ro
      - /etc/letsencrypt/archive/cubevisservice.site:/etc/letsencrypt/archive/cubevisservice.site:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "https://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - websocket-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  websocket-network:
    driver: bridge
